### ISSUE TITLE
Stairs/Slabs/Walls Don't Automatically Apply emissiveLighting

### ISSUE THREAD

**Issue by sylv256** [ProtonMC/Proton#29]
When you apply the `emissiveLighting` property to a block and add a stair/slab/wall variant of it, the stairs/slabs/walls won't have `emissiveLighting`.

**Comment by namebee** [comment]
If no one looks at this before I do, I’ll look into it tomorrow.

**Comment by sylv256** [comment]
(btw don't forget to add the label :tiny_potato:)

**Comment by YTG1234** [comment]
Looks like we gotta mixin to the block settings

**Comment by YTG1234** [comment]
or do it manually

**Comment by sylv256** [comment]
Fixed
