### ISSUE TITLE
Make the config save button change the module fields at runtime

### ISSUE THREAD

**Issue by YTG1234** [ProtonMC/Proton#31]
Currently, when pressing the save button in the config screen it updates the JSON but not the fields inside the `ProtonModule`s themselves.
That means the player has to restart Minecraft in order to apply the changes.

To make it modify the fields at runtime, this can be achieved by calling `fromJson` again.

**Comment by dzwdz** [comment]
...it changes the fields though? i just tried it with the campfire elytra tweak and it works fine
