### ISSUE TITLE
Add Checkstyle

### ISSUE THREAD

**Issue by BoogieMonster1O1** [ProtonMC/Proton#7]
Most merge conflicts will occur because of the import order and blank lines.
A simple checkstyle config can be found here: https://github.com/FabricMC/fabric/blob/1.16/checkstyle.xml

**Comment by hYdos** [comment]
IDEA default is the formatting used. we are not using the concern which is fabric api checkstyle.

**Comment by BoogieMonster1O1** [comment]
> IDEA default is the formatting used. we are not using the concern which is fabric api checkstyle.

merge conflicts
