### ISSUE TITLE
JDK 9+ users can't build the mod because one of the classes is named Module

### ISSUE THREAD

**Issue by BoogieMonster1O1** [ProtonMC/Proton#8]
`Module` is a class in the `java.lang` package in java 9+. This means that 
- the mod won't be able to build without providing fully qualified class names
- the mod will have a lot of warnings because `Module` only exists in java 9+ and the language level is almost always set to 8

**Comment by sylv256** [comment]
Ideally, you should be using Java 8.

**Comment by hYdos** [comment]
![image](https://user-images.githubusercontent.com/25501603/95033979-62ded880-0703-11eb-94b6-421fc11a2f8a.png)
im using jdk 14 fine.

**Comment by BoogieMonster1O1** [comment]
I’m using jdk 11 and it’s not fine
especially those classes in the same directory as Module
and the api level warnings are bad

**Comment by hYdos** [comment]
concern. why jdk 11? thats a big of an odd release isnt it? usually your using jdk 8 or some version around the latest

**Comment by BoogieMonster1O1** [comment]
> concern. why jdk 11? thats a big of an odd release isnt it? usually your using jdk 8 or some version around the latest

I tested this with nine eleven and fifteen
Modules were introduced in nine btw
eleven has dcevm

**Comment by hYdos** [comment]
just tested jdk 9 and it works fine. this is a mac jdk issue

**Comment by BoogieMonster1O1** [comment]
lemme send a screenshot

**Comment by hYdos** [comment]
this is a mac issue. i also have this running on windows. unless you can replicate it on another os its a mac problem

**Comment by BoogieMonster1O1** [comment]
explain
![image](https://user-images.githubusercontent.com/62552372/95035284-3cf50c00-06e2-11eb-9a58-d6f77c2287a3.png)
![image](https://user-images.githubusercontent.com/62552372/95035291-42eaed00-06e2-11eb-8c11-ebbccba1eba8.png)

**Comment by namebee** [comment]
I’ve been using JDK 11 on Windows 10 and it’s completely fine, I’ll try on MacOS in a bit.

**Comment by namebee** [comment]
Tested on MacOS JDK 11 and 8, No issues. This is a problem with your machine.

**Comment by nnym** [comment]
You shouldn't name a class the same as a class in the `java.lang` package. I suggest using `Component` or `Element` instead.

**Comment by namebee** [comment]
Module has been renamed to ProtonModule.
